//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannelAdvisor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EMGExtractor_OutputFolder {
            get {
                return ((string)(this["EMGExtractor_OutputFolder"]));
            }
            set {
                this["EMGExtractor_OutputFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WynitBasicData_OutputFolder {
            get {
                return ((string)(this["WynitBasicData_OutputFolder"]));
            }
            set {
                this["WynitBasicData_OutputFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wynit")]
        public string WynitBasicData_SupplierCode {
            get {
                return ((string)(this["WynitBasicData_SupplierCode"]));
            }
            set {
                this["WynitBasicData_SupplierCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wynit")]
        public string WynitBasicData_WarehouseLocation {
            get {
                return ((string)(this["WynitBasicData_WarehouseLocation"]));
            }
            set {
                this["WynitBasicData_WarehouseLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wynit")]
        public string WynitBasicData_DCCode {
            get {
                return ((string)(this["WynitBasicData_DCCode"]));
            }
            set {
                this["WynitBasicData_DCCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public int PicnicTimeExtractor_AuctionTitleLength {
            get {
                return ((int)(this["PicnicTimeExtractor_AuctionTitleLength"]));
            }
            set {
                this["PicnicTimeExtractor_AuctionTitleLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int PicnicTimeExtractor_CAStoreTitleLength {
            get {
                return ((int)(this["PicnicTimeExtractor_CAStoreTitleLength"]));
            }
            set {
                this["PicnicTimeExtractor_CAStoreTitleLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://s253.photobucket.com/albums/hh64/bargainsdelivered/PicnicTime/")]
        public string PicnicTimeExtractor_ImageURLs {
            get {
                return ((string)(this["PicnicTimeExtractor_ImageURLs"]));
            }
            set {
                this["PicnicTimeExtractor_ImageURLs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.50")]
        public string PicnicTimeExtractor_SellectCostAddition {
            get {
                return ((string)(this["PicnicTimeExtractor_SellectCostAddition"]));
            }
            set {
                this["PicnicTimeExtractor_SellectCostAddition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Picnic Time")]
        public string PicnicTimeExtractor_SupplierCode {
            get {
                return ((string)(this["PicnicTimeExtractor_SupplierCode"]));
            }
            set {
                this["PicnicTimeExtractor_SupplierCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Picnic Time")]
        public string PicnicTimeExtractor_WarehouseLocation {
            get {
                return ((string)(this["PicnicTimeExtractor_WarehouseLocation"]));
            }
            set {
                this["PicnicTimeExtractor_WarehouseLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Picnic Time")]
        public string PicnicTimeExtractor_DCCode {
            get {
                return ((string)(this["PicnicTimeExtractor_DCCode"]));
            }
            set {
                this["PicnicTimeExtractor_DCCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PicnicTimeExtractor_FilePrefix {
            get {
                return ((string)(this["PicnicTimeExtractor_FilePrefix"]));
            }
            set {
                this["PicnicTimeExtractor_FilePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PicnicTimeExtractor_OutputFolder {
            get {
                return ((string)(this["PicnicTimeExtractor_OutputFolder"]));
            }
            set {
                this["PicnicTimeExtractor_OutputFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SunpentownExtractor_OutputFolder {
            get {
                return ((string)(this["SunpentownExtractor_OutputFolder"]));
            }
            set {
                this["SunpentownExtractor_OutputFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public int SunpentownExtractor_AuctionTitleLength {
            get {
                return ((int)(this["SunpentownExtractor_AuctionTitleLength"]));
            }
            set {
                this["SunpentownExtractor_AuctionTitleLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int SunpentownExtractor_CAStoreTitleLength {
            get {
                return ((int)(this["SunpentownExtractor_CAStoreTitleLength"]));
            }
            set {
                this["SunpentownExtractor_CAStoreTitleLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://i253.photobucket.com/albums/hh64/bargainsdelivered/Sunpentown/")]
        public string SunpentownExtractor_ImageURLs {
            get {
                return ((string)(this["SunpentownExtractor_ImageURLs"]));
            }
            set {
                this["SunpentownExtractor_ImageURLs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SPT")]
        public string SunpentownExtractor_SupplierCode {
            get {
                return ((string)(this["SunpentownExtractor_SupplierCode"]));
            }
            set {
                this["SunpentownExtractor_SupplierCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SPT")]
        public string SunpentownExtractor_WarehouseLocation {
            get {
                return ((string)(this["SunpentownExtractor_WarehouseLocation"]));
            }
            set {
                this["SunpentownExtractor_WarehouseLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SPT")]
        public string SunpentownExtractor_DCCode {
            get {
                return ((string)(this["SunpentownExtractor_DCCode"]));
            }
            set {
                this["SunpentownExtractor_DCCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SunpentownExtractor_FilePrefix {
            get {
                return ((string)(this["SunpentownExtractor_FilePrefix"]));
            }
            set {
                this["SunpentownExtractor_FilePrefix"] = value;
            }
        }
    }
}
